=== BuildingSMART/BCF/Schemas/extensions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="shared-types.xsd"/>

    <xs:element name="Extensions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TopicTypes" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TopicType" type="TopicType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="TopicStatuses" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TopicStatus" type="NonEmptyOrBlankString" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Priorities" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Priority" type="NonEmptyOrBlankString" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="TopicLabels" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TopicLabel" type="NonEmptyOrBlankString" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="User" type="NonEmptyOrBlankString" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Stages" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Stage" type="NonEmptyOrBlankString" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TopicType">
        <xs:simpleContent>
            <xs:extension base="NonEmptyOrBlankString">
                <xs:attribute name="StatusType" type="TopicLabelEnum" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
        <xs:simpleType name="TopicLabelEnum">
            <xs:restriction base="xs:string">
                <xs:enumeration value="open"/>
                <xs:enumeration value="closed"/>
            </xs:restriction>
        </xs:simpleType>
</xs:schema>

=== BuildingSMART/BCF/Test Cases/v3.0/Visualization/All parts of curtain wall visible/unzipped/extensions.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Extensions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="extensions.xsd">
    <TopicTypes>
        <TopicType>Error</TopicType>
        <TopicType>Warning</TopicType>
        <TopicType>Info</TopicType>
        <TopicType>Clash</TopicType>
    </TopicTypes>
    <TopicStatuses>
        <TopicStatus>Open</TopicStatus>
        <TopicStatus>In_progress</TopicStatus>
        <TopicStatus>Solved</TopicStatus>
        <TopicStatus>Closed</TopicStatus>
    </TopicStatuses>
    <Priorities>
        <Priority>Low</Priority>
        <Priority>Medium</Priority>
        <Priority>High</Priority>
        <Priority>Critical</Priority>
    </Priorities>
    <TopicLabels/>
    <Users>
        <User>Architect@example.com</User>
        <User>Engineer@example.com</User>
        <User>MEPDesigner@example.com</User>
    </Users>
    <SnippetTypes/>
    <Stages/>
</Extensions>
